"""add group type/description and submit node groups

Revision ID: 026216ef4d8a
Revises: f2ec55925c4c
Create Date: 2026-05-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '026216ef4d8a'
down_revision: Union[str, Sequence[str], None] = 'f2ec55925c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GROUPS_DATA = [
    {'node_name': 'wright-ap4000.chtc.wisc.edu', 'group_name': 'wright-ap-login', 'description': 'Access to wright-ap4000.chtc.wisc.edu'},
    {'node_name': 'townsend-submit.chtc.wisc.edu', 'group_name': 'townsend-ap-login', 'description': 'Access to townsend-submit.chtc.wisc.edu'},
    {'node_name': 'hpclogin1.chtc.wisc.edu', 'group_name': 'spark-login', 'description': 'Access to hpclogin1.chtc.wisc.edu'},
    {'node_name': 'osg-sw-submit.chtc.wisc.edu', 'group_name': 'osgsw-ap-login', 'description': 'Access to osg-sw-submit.chtc.wisc.edu'},
    {'node_name': 'oconnor-ap.chtc.wisc.edu', 'group_name': 'oconnor-ap-login', 'description': 'Access to oconnor-ap.chtc.wisc.edu'},
    {'node_name': 'learn.chtc.wisc.edu', 'group_name': 'learn-ap-login', 'description': 'Access to learn.chtc.wisc.edu'},
    {'node_name': 'htc_transfer', 'group_name': 'htc-transfer-login', 'description': 'Access to htc_transfer'},
    {'node_name': 'ap2002.chtc.wisc.edu', 'group_name': 'ap2002-login', 'description': 'Access to ap2002.chtc.wisc.edu'},
    {'node_name': 'ap2001.chtc.wisc.edu', 'group_name': 'ap2001-login', 'description': 'Access to ap2001.chtc.wisc.edu'},
]

group_type_enum = postgresql.ENUM(
    'SUBMIT_NODE',
    name='group_type_enum',
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    group_type_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('type', group_type_enum, nullable=True))
    # ### end Alembic commands ###

    # ### commands generated by human - please check for typos! ###
    values_list_string = ",\n".join(
        f"('{g['group_name']}', '{g['description']}', 'SUBMIT_NODE'::group_type_enum)"
        for g in GROUPS_DATA
    )

    op.execute(f"""
        INSERT INTO groups (name, description, type)
        VALUES
        {values_list_string}
        ON CONFLICT (name) DO NOTHING
    """)

    mapping_list_string = ",\n".join(
        f"('{g['node_name']}', '{g['group_name']}')" 
        for g in GROUPS_DATA
    )

    op.execute(f"""
        INSERT INTO user_groups (user_id, group_id, managed_by)
        SELECT DISTINCT
            us.user_id,
            g.id,
            'APPLICATION'::entity_manager_enum
        FROM user_submits us
        INNER JOIN submit_nodes sn ON sn.id = us.submit_node_id
        INNER JOIN (
            VALUES
            {mapping_list_string}
        ) AS mapping(node_name, group_name) ON sn.name = mapping.node_name
        INNER JOIN groups g ON g.name = mapping.group_name
        ON CONFLICT ON CONSTRAINT user_groups_distinct DO NOTHING
    """)

    op.execute("""
        CREATE OR REPLACE VIEW user_group_memberships AS
        SELECT
            ug.group_id,
            ug.user_id,
            ug.managed_by,
            ug.created_at,
            ug.updated_at,
            g.name,
            g.description,
            g.point_of_contact,
            g.unix_gid,
            g.has_groupdir,
            g.type
        FROM user_groups ug
        JOIN groups g ON ug.group_id = g.id
    """)
    # ### end commands generated by human ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands generated by human - please check for typos! ###
    group_names_string = ', '.join(f"'{group['group_name']}'" for group in GROUPS_DATA)

    op.execute(f"""
        DELETE FROM user_groups
        WHERE group_id IN (
            SELECT id FROM groups
            WHERE name IN ({group_names_string})
              AND type = 'SUBMIT_NODE'::group_type_enum
        )
    """)

    op.execute(f"""
        DELETE FROM groups
        WHERE name IN ({group_names_string})
          AND type = 'SUBMIT_NODE'::group_type_enum
    """)

    op.execute("""
        CREATE OR REPLACE VIEW user_group_memberships AS
        SELECT
            ug.group_id,
            ug.user_id,
            ug.managed_by,
            ug.created_at,
            ug.updated_at,
            g.name,
            g.point_of_contact,
            g.unix_gid,
            g.has_groupdir
        FROM user_groups ug
        JOIN groups g ON ug.group_id = g.id
    """)
    # ### end commands generated by human ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'type')
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###

    bind = op.get_bind()
    group_type_enum.drop(bind, checkfirst=True)