"""add group type/description and submit node groups

Revision ID: 026216ef4d8a
Revises: f2ec55925c4c
Create Date: 2026-05-29

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '026216ef4d8a'
down_revision: Union[str, Sequence[str], None] = 'f2ec55925c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


GROUPS_DATA = [
    {'node_name': 'wright-ap4000.chtc.wisc.edu', 'group_name': 'wright-ap-login', 'description': 'Access to wright-ap4000.chtc.wisc.edu'},
    {'node_name': 'townsend-submit.chtc.wisc.edu', 'group_name': 'townsend-ap-login', 'description': 'Access to townsend-submit.chtc.wisc.edu'},
    {'node_name': 'hpclogin1.chtc.wisc.edu', 'group_name': 'spark-login', 'description': 'Access to hpclogin1.chtc.wisc.edu'},
    {'node_name': 'osg-sw-submit.chtc.wisc.edu', 'group_name': 'osgsw-ap-login', 'description': 'Access to osg-sw-submit.chtc.wisc.edu'},
    {'node_name': 'oconnor-ap.chtc.wisc.edu', 'group_name': 'oconnor-ap-login', 'description': 'Access to oconnor-ap.chtc.wisc.edu'},
    {'node_name': 'learn.chtc.wisc.edu', 'group_name': 'learn-ap-login', 'description': 'Access to learn.chtc.wisc.edu'},
    {'node_name': 'htc_transfer', 'group_name': 'htc-transfer-login', 'description': 'Access to htc_transfer'},
    {'node_name': 'ap2002.chtc.wisc.edu', 'group_name': 'ap2002-login', 'description': 'Access to ap2002.chtc.wisc.edu'},
    {'node_name': 'ap2001.chtc.wisc.edu', 'group_name': 'ap2001-login', 'description': 'Access to ap2001.chtc.wisc.edu'},
]

group_type_enum = postgresql.ENUM(
    'SUBMIT_NODE',
    name='group_type_enum',
    create_type=False,
)

def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    group_type_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('type', group_type_enum, nullable=True))
    # ### end Alembic commands ###

    # ### commands generated by human - please check for typos! ###
    values_list_string = ",\n".join(
        f"('{g['group_name']}', '{g['description']}', 'SUBMIT_NODE'::group_type_enum, FALSE)"
        for g in GROUPS_DATA
    )

    op.execute(f"""
        INSERT INTO groups (name, description, type, has_groupdir)
        VALUES
        {values_list_string}
        ON CONFLICT (name) DO NOTHING
    """)

    mapping_list_string = ",\n".join(
        f"('{g['node_name']}', '{g['group_name']}')" 
        for g in GROUPS_DATA
    )

    op.execute(f"""
        INSERT INTO user_groups (user_id, group_id, managed_by)
        SELECT DISTINCT
            us.user_id,
            g.id,
            'APPLICATION'::entity_manager_enum
        FROM user_submits us
        INNER JOIN submit_nodes sn ON sn.id = us.submit_node_id
        INNER JOIN (
            VALUES
            {mapping_list_string}
        ) AS mapping(node_name, group_name) ON sn.name = mapping.node_name
        INNER JOIN groups g ON g.name = mapping.group_name
        ON CONFLICT ON CONSTRAINT user_groups_distinct DO NOTHING
    """)

    op.execute("DROP VIEW IF EXISTS user_group_memberships")
    op.execute("""
        CREATE VIEW user_group_memberships AS
        SELECT
            ug.group_id,
            ug.user_id,
            ug.managed_by,
            ug.created_at,
            ug.updated_at,
            g.name,
            g.description,
            g.point_of_contact,
            g.unix_gid,
            g.has_groupdir,
            g.type
        FROM user_groups ug
        JOIN groups g ON ug.group_id = g.id
    """)

    # Drop the now-replaced submit node objects. Submit node access is represented as
    # membership in a SUBMIT_NODE-typed group (backfilled above), so these are obsolete.
    # Order matters: dependent view first, then child table, then parent table.
    op.execute("DROP VIEW IF EXISTS user_submit_nodes")
    op.execute("DROP TABLE IF EXISTS user_submits")
    op.execute("DROP TABLE IF EXISTS submit_nodes")
    # ### end commands generated by human ###


def downgrade() -> None:
    """Downgrade schema."""

    # ### commands generated by human - please check for typos! ###

    # Recreate the submit node objects that upgrade() dropped, restoring the pre-migration
    # schema (reverse order of the drops: parent table, child table, then the view).
    # NOTE: this restores schema only, not the dropped data (it was migrated into groups).
    # NOTE: the user_submit_nodes view body is reconstructed from the ORM model columns -- the
    # original was created pre-Alembic and is in no migration. Confirm against
    # `SELECT pg_get_viewdef('user_submit_nodes'::regclass, true);` if exact fidelity is needed.
    op.execute("""
        CREATE TABLE IF NOT EXISTS submit_nodes (
            id SERIAL PRIMARY KEY,
            name VARCHAR(60)
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS user_submits (
            id SERIAL PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            submit_node_id INTEGER NOT NULL REFERENCES submit_nodes(id) ON DELETE CASCADE,
            for_auth_netid BOOLEAN,
            disk_quota INTEGER,
            hpc_diskquota INTEGER NOT NULL DEFAULT 100,
            hpc_inodequota INTEGER NOT NULL DEFAULT 50000,
            hpc_joblimit INTEGER NOT NULL DEFAULT 10,
            hpc_corelimit INTEGER NOT NULL DEFAULT 720,
            hpc_fairshare INTEGER NOT NULL DEFAULT 100,
            CONSTRAINT user_submits_distinct UNIQUE (user_id, submit_node_id, for_auth_netid)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_submits_submit_node_id ON user_submits (submit_node_id)")
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_user_submits_userid_submitnodeid_incl
        ON user_submits (user_id, submit_node_id)
        INCLUDE (disk_quota, hpc_diskquota, hpc_inodequota, hpc_joblimit, hpc_corelimit, hpc_fairshare)
    """)

    op.execute("""
        CREATE OR REPLACE VIEW user_submit_nodes AS
        SELECT
            us.user_id,
            us.submit_node_id,
            sn.name AS submit_node_name,
            us.disk_quota,
            us.hpc_diskquota,
            us.hpc_inodequota,
            us.hpc_joblimit,
            us.hpc_corelimit,
            us.hpc_fairshare
        FROM user_submits us
        JOIN submit_nodes sn ON sn.id = us.submit_node_id
    """)

    group_names_string = ', '.join(f"'{group['group_name']}'" for group in GROUPS_DATA)

    op.execute(f"""
        DELETE FROM user_groups
        WHERE group_id IN (
            SELECT id FROM groups
            WHERE name IN ({group_names_string})
              AND type = 'SUBMIT_NODE'::group_type_enum
        )
    """)

    op.execute(f"""
        DELETE FROM groups
        WHERE name IN ({group_names_string})
          AND type = 'SUBMIT_NODE'::group_type_enum
    """)

    op.execute("DROP VIEW IF EXISTS user_group_memberships")
    op.execute("""
        CREATE VIEW user_group_memberships AS
        SELECT
            ug.group_id,
            ug.user_id,
            ug.managed_by,
            ug.created_at,
            ug.updated_at,
            g.name,
            g.point_of_contact,
            g.unix_gid,
            g.has_groupdir
        FROM user_groups ug
        JOIN groups g ON ug.group_id = g.id
    """)
    # ### end commands generated by human ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'type')
    op.drop_column('groups', 'description')
    # ### end Alembic commands ###

    bind = op.get_bind()
    group_type_enum.drop(bind, checkfirst=True)