"""Add indices where needed

Revision ID: 4aa2a7d34719
Revises: cf94844cecc1
Create Date: 2026-04-22 15:52:30.483923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aa2a7d34719'
down_revision: Union[str, Sequence[str], None] = 'cf94844cecc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_access_token_id'), 'access', ['token_id'], unique=False)
    op.create_index(op.f('ix_access_user_id'), 'access', ['user_id'], unique=False)
    op.create_index(op.f('ix_forms_created_by'), 'forms', ['created_by'], unique=False)
    op.create_index(op.f('ix_forms_form_type'), 'forms', ['form_type'], unique=False)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_index(op.f('ix_forms_updated_by'), 'forms', ['updated_by'], unique=False)
    op.create_index(op.f('ix_groups_point_of_contact'), 'groups', ['point_of_contact'], unique=False)
    op.create_index(op.f('ix_notes_author'), 'notes', ['author'], unique=False)
    op.create_index(op.f('ix_projects_accounting_group'), 'projects', ['accounting_group'], unique=False)
    op.create_index(op.f('ix_projects_pi'), 'projects', ['pi'], unique=False)
    op.create_index(op.f('ix_projects_staff1'), 'projects', ['staff1'], unique=False)
    op.create_index(op.f('ix_projects_staff2'), 'projects', ['staff2'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_tokens_created_by'), 'tokens', ['created_by'], unique=False)
    op.create_index(op.f('ix_tokens_expires_at'), 'tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_form_pi_id'), 'user_form', ['pi_id'], unique=False)
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index('ix_user_notes_note_id', 'user_notes', ['note_id'], unique=False)
    op.create_index('ix_user_notes_project_id', 'user_notes', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_projects_project_id'), 'user_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_user_submits_submit_node_id'), 'user_submits', ['submit_node_id'], unique=False)
    op.create_index('ix_users_active', 'users', ['active'], unique=False)
    op.create_index('ix_users_email1', 'users', ['email1'], unique=False)
    op.create_index('ix_users_unix_uid', 'users', ['unix_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_unix_uid', table_name='users')
    op.drop_index('ix_users_email1', table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.drop_index(op.f('ix_user_submits_submit_node_id'), table_name='user_submits')
    op.drop_index(op.f('ix_user_projects_project_id'), table_name='user_projects')
    op.drop_index('ix_user_notes_project_id', table_name='user_notes')
    op.drop_index('ix_user_notes_note_id', table_name='user_notes')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_form_pi_id'), table_name='user_form')
    op.drop_index(op.f('ix_tokens_expires_at'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_created_by'), table_name='tokens')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_staff2'), table_name='projects')
    op.drop_index(op.f('ix_projects_staff1'), table_name='projects')
    op.drop_index(op.f('ix_projects_pi'), table_name='projects')
    op.drop_index(op.f('ix_projects_accounting_group'), table_name='projects')
    op.drop_index(op.f('ix_notes_author'), table_name='notes')
    op.drop_index(op.f('ix_groups_point_of_contact'), table_name='groups')
    op.drop_index(op.f('ix_forms_updated_by'), table_name='forms')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_form_type'), table_name='forms')
    op.drop_index(op.f('ix_forms_created_by'), table_name='forms')
    op.drop_index(op.f('ix_access_user_id'), table_name='access')
    op.drop_index(op.f('ix_access_token_id'), table_name='access')
    # ### end Alembic commands ###
