"""Add JSON field for dynamic form contents

Revision ID: 6450d7ab8865
Revises: f91affa16676
Create Date: 2026-04-13 11:01:09.921781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6450d7ab8865'
down_revision: Union[str, Sequence[str], None] = 'f91affa16676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_form', sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###

    # ### commands generated by human ###
    op.execute("""
       CREATE VIEW user_applications AS
       SELECT f.id,
              f.form_type,
              f.status,
              f.created_by,
              f.created_at,
              f.updated_by,
              f.updated_at,
              uf.pi_id,
              uf.pi_name,
              uf.pi_email,
              uf.position,
              uf.content
       FROM forms f
                JOIN user_form uf ON f.id = uf.id
       WHERE f.form_type = 'USER'
    """)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands generated by human ###
    op.execute("DROP VIEW IF EXISTS user_applications")
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_form', 'content')
    # ### end Alembic commands ###
