"""Move access table to use JSONB for payload

Revision ID: a095c68f3ad3
Revises: b8ae04f033ae
Create Date: 2026-03-06 11:07:27.467598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a095c68f3ad3'
down_revision: Union[str, Sequence[str], None] = 'b8ae04f033ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('access', 'payload',
               existing_type=sa.VARCHAR(length=255),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_nullable=True,
               postgresql_using="payload::jsonb")
    op.drop_column('access', 'expires_at')
    op.add_column('access', sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_request_method_enum', create_type=False), nullable=False))
    op.add_column('access', sa.Column('query_string', sa.String(length=2048), nullable=True))
    op.add_column('access', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access', 'status')
    op.drop_column('access', 'query_string')
    op.drop_column('access', 'method')
    op.add_column('access', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('access', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               existing_nullable=True)
    # ### end Alembic commands ###
