"""remove_username_and_password_from_users

Revision ID: b8ae04f033ae
Revises: a674e0eb726a
Create Date: 2026-02-13 13:48:21.729485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ae04f033ae'
down_revision: Union[str, Sequence[str], None] = 'a674e0eb726a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop constraints that reference username or password before dropping the columns
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_username_or_netid_not_null')
    op.execute('ALTER TABLE users DROP CONSTRAINT IF EXISTS chk_password_if_username_not_null')

    # Drop views that depend on username before altering the table
    op.execute('DROP VIEW IF EXISTS joined_projects')
    op.execute('DROP VIEW IF EXISTS pi_projects')

    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')

    # Recreate joined_projects view without username
    op.execute("""
        CREATE VIEW joined_projects AS
            SELECT
                u.id,
                p.id AS project_id,
                p.name AS project_name,
                p.staff1 AS project_staff1,
                p.staff2 AS project_staff2,
                p.status AS project_status,
                p.last_contact AS project_last_contact,
                p.accounting_group AS project_accounting_group,
                up.is_primary AS is_primary,
                u.name,
                u.email1,
                u.email2,
                u.netid,
                u.netid_exp_datetime,
                u.phone1,
                u.phone2,
                u.is_admin,
                u.active,
                u.date,
                u.unix_uid,
                u.position,
                up.role,
                ( SELECT n.ticket FROM notes n LEFT JOIN user_notes un ON n.id = un.note_id WHERE un.user_id = up.user_id AND un.project_id = up.project_id ORDER BY n.id DESC LIMIT 1 ) AS last_note_ticket
            FROM user_projects up
            JOIN users u ON up.user_id = u.id
            JOIN projects p ON up.project_id = p.id
    """)

    # Recreate pi_projects view without username
    op.execute("""
        CREATE VIEW pi_projects AS
        SELECT
            u.id AS user_id,
            u.name,
            u.email1,
            u.netid,
            u.phone1,
            p.id AS project_id,
            p.name AS project_name
        FROM users u
        JOIN user_projects up ON up.user_id = u.id
        JOIN projects p ON p.id = up.project_id
        WHERE up.role = 'PI'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop views before restoring the columns
    op.execute('DROP VIEW IF EXISTS joined_projects')
    op.execute('DROP VIEW IF EXISTS pi_projects')

    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)

    # Recreate joined_projects view with username
    op.execute("""
        CREATE VIEW joined_projects AS
            SELECT
                u.id,
                p.id AS project_id,
                p.name AS project_name,
                p.staff1 AS project_staff1,
                p.staff2 AS project_staff2,
                p.status AS project_status,
                p.last_contact AS project_last_contact,
                p.accounting_group AS project_accounting_group,
                up.is_primary AS is_primary,
                u.username,
                u.name,
                u.email1,
                u.email2,
                u.netid,
                u.netid_exp_datetime,
                u.phone1,
                u.phone2,
                u.is_admin,
                u.active,
                u.date,
                u.unix_uid,
                u.position,
                up.role,
                ( SELECT n.ticket FROM notes n LEFT JOIN user_notes un ON n.id = un.note_id WHERE un.user_id = up.user_id AND un.project_id = up.project_id ORDER BY n.id DESC LIMIT 1 ) AS last_note_ticket
            FROM user_projects up
            JOIN users u ON up.user_id = u.id
            JOIN projects p ON up.project_id = p.id
    """)

    # Recreate pi_projects view with username
    op.execute("""
        CREATE VIEW pi_projects AS
        SELECT
            u.id AS user_id,
            u.username,
            u.name,
            u.email1,
            u.netid,
            u.phone1,
            p.id AS project_id,
            p.name AS project_name
        FROM users u
        JOIN user_projects up ON up.user_id = u.id
        JOIN projects p ON p.id = up.project_id
        WHERE up.role = 'PI'
    """)

    # Restore original constraints
    op.execute("ALTER TABLE users ADD CONSTRAINT chk_username_or_netid_not_null CHECK (username IS NOT NULL OR netid IS NOT NULL) NOT VALID")
    op.execute("ALTER TABLE users ADD CONSTRAINT chk_password_if_username_not_null CHECK (username IS NULL OR password IS NOT NULL) NOT VALID")
    # ### end Alembic commands ###
