"""Add Token Scopes

Revision ID: cd61b41c6c55
Revises: 1d68d572169d
Create Date: 2026-02-11 12:05:51.935780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd61b41c6c55'
down_revision: Union[str, Sequence[str], None] = '1d68d572169d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_request_method_enum'), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'method', 'route', name='token_permissions_distinct')
    )
    op.create_index(op.f('ix_token_permissions_id'), 'token_permissions', ['id'], unique=False)
    op.create_index('ix_token_permissions_token_id', 'token_permissions', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_permissions_token_id', table_name='token_permissions')
    op.drop_index(op.f('ix_token_permissions_id'), table_name='token_permissions')
    op.drop_table('token_permissions')
    op.execute("DROP TYPE IF EXISTS http_request_method_enum")
    # ### end Alembic commands ###
