"""Allow email1 to be nullable

Revision ID: cf94844cecc1
Revises: 6450d7ab8865
Create Date: 2026-04-20 11:48:33.276491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf94844cecc1'
down_revision: Union[str, Sequence[str], None] = '6450d7ab8865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_form', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email1',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### commands generated by human ###

    # This view exists, drop and create anew
    op.execute("DROP VIEW IF EXISTS user_applications")

    # Create view with email field
    op.execute("""
       CREATE VIEW user_applications AS
       SELECT f.id,
              f.form_type,
              f.status,
              f.created_by,
              f.created_at,
              f.updated_by,
              f.updated_at,
              uf.email,
              uf.pi_id,
              uf.pi_name,
              uf.pi_email,
              uf.position,
              uf.content
       FROM forms f
                JOIN user_form uf ON f.id = uf.id
       WHERE f.form_type = 'USER'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands generated by human ###
    op.execute("DROP VIEW IF EXISTS user_applications")
    op.execute("""
       CREATE VIEW user_applications AS
       SELECT f.id,
              f.form_type,
              f.status,
              f.created_by,
              f.created_at,
              f.updated_by,
              f.updated_at,
              uf.pi_id,
              uf.pi_name,
              uf.pi_email,
              uf.position,
              uf.content
       FROM forms f
                JOIN user_form uf ON f.id = uf.id
       WHERE f.form_type = 'USER'
    """)
    # ### end Alembic commands ###

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email1',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('user_form', 'email')
    # ### end Alembic commands ###


