"""Basic forms

Revision ID: f91affa16676
Revises: b8ae04f033ae
Create Date: 2026-03-31 12:50:41.854864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91affa16676'
down_revision: Union[str, Sequence[str], None] = 'b8ae04f033ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_type', sa.Enum('USER', 'PROJECT', name='form_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='form_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_id'), 'forms', ['id'], unique=False)
    op.create_table('user_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_notes_userid_noteid_desc', 'user_notes', ['user_id', 'note_id'], unique=False, postgresql_using='btree')
    op.create_index('idx_user_notes_userid_projectid_noteid', 'user_notes', ['user_id', 'project_id', 'note_id'], unique=False)
    op.create_index('idx_user_submits_userid_submitnodeid_incl', 'user_submits', ['user_id', 'submit_node_id'], unique=False, postgresql_include=['disk_quota', 'hpc_diskquota', 'hpc_inodequota', 'hpc_joblimit', 'hpc_corelimit', 'hpc_fairshare'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_submits_userid_submitnodeid_incl', table_name='user_submits', postgresql_include=['disk_quota', 'hpc_diskquota', 'hpc_inodequota', 'hpc_joblimit', 'hpc_corelimit', 'hpc_fairshare'])
    op.drop_index('idx_user_notes_userid_projectid_noteid', table_name='user_notes')
    op.drop_index('idx_user_notes_userid_noteid_desc', table_name='user_notes', postgresql_using='btree')
    op.drop_table('user_form')
    op.drop_index(op.f('ix_forms_id'), table_name='forms')
    op.drop_table('forms')
    # ### end Alembic commands ###
